#!/bin/bash -e

function usage() {
	echo "$0 <username> <password>"
}

[ ! $# -eq 2 ] && usage && exit 0

sudo kcpassword "$2"
sudo /usr/bin/defaults write /Library/Preferences/com.apple.loginwindow autoLoginUser "$1"