#!/bin/bash

function usage() {
	echo "$0 <username> <password>"
}

[ ! $# -eq 2 ] && usage && exit 0

sudo kcpassword "$1"
sudo /usr/bin/defaults write /Library/Preferences/com.apple.loginwindow autoLoginUser "$0"